from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any


@dataclass
class QuizQuestion:
    """A single quiz question generated by QuizAgent."""

    id: str
    type: str  # single_choice | multiple_choice | fill_blank | true_false
    stem: str  # 题干
    options: list[dict] | None = None  # [{"id": "A", "text": "..."}, ...]
    answer: str = ""  # 正确答案
    explanation: str = ""  # 解析
    knowledge_point: str = ""  # 所属知识点
    difficulty: int = 2  # 1~5
    source: dict | None = None  # {"document_id": "...", "chunk_id": "..."}


@dataclass
class QuizEvaluation:
    """Evaluation result after a user completes a quiz."""

    score: float = 0.0  # 百分制
    correct_count: int = 0
    total_count: int = 0
    weak_points: list[str] = field(default_factory=list)
    suggestions: list[str] = field(default_factory=list)
    details: list[dict] = field(default_factory=list)  # 逐题批改明细
