from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any


@dataclass
class Slide:
    """A single slide in the PPT outline."""

    title: str  # 幻灯片标题
    bullets: list[str] = field(default_factory=list)  # 要点列表
    speaker_notes: str = ""  # 讲稿或复习提示
    source_chunks: list[str] = field(default_factory=list)  # 关联的知识库 chunk ID


@dataclass
class PptOutline:
    """Complete PPT outline generated by PPTAgent."""

    title: str  # PPT 总标题
    slides: list[Slide] = field(default_factory=list)  # 幻灯片列表
    slide_count: int = 0
    topic: str = ""
    summary: str = ""  # 整体摘要
